name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Delio-DevOps
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push to main
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake animation"
          add: "dist"
          default_author: github_actions
